### ISSUE TITLE
Documentation not available online

### ISSUE THREAD

**Issue by halleycarleton** [louderthanten/livewires#3]
http://guide.livewires.io/ does not load, it returns `ERR_CONNECTION_TIMED_OUT`. Without that it's hard to tell what Live Wires actually does without downloading it and finding the included guide from the default project index.

The example at http://guide.io/example/index, which is linked in `/httpdocs/index.html`, returns the same error.

**Comment by louderthan10** [comment]
Hey thanks for the heads up. I've just fixed the [guide](http://guide.livewires.io). We've got some nice updates planned, so stay tuned!
