### ISSUE TITLE
Warning: NoMethodError

### ISSUE THREAD

**Issue by mindmergedesign** [louderthanten/livewires#5]
I get the following error after running grunt serve:

Warning: NoMethodError: undefined method `specificity' for [:not(.collapse)]:Array
Use --trace for backtrace. Use --force to continue.

Aborted due to warnings.

**Comment by louderthan10** [comment]
Hi @mindmergedesign,

Sorry for the late reply. Looks like this is an issue in an [older version of Sass](https://github.com/sass/sass/issues/1476). Can you try and update to the latest version and try running again?

Thanks!
